# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.com.kodfarki.subscreasy.client.model.profile_info_vm import ProfileInfoVM  # noqa: E501
from swagger_client.rest import ApiException


class TestProfileInfoVM(unittest.TestCase):
    """ProfileInfoVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfileInfoVM(self):
        """Test ProfileInfoVM"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.profile_info_vm.ProfileInfoVM()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
