# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.offer_resource_api import OfferResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOfferResourceApi(unittest.TestCase):
    """OfferResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.offer_resource_api.OfferResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_offer_using_post(self):
        """Test case for create_offer_using_post

        createOffer  # noqa: E501
        """
        pass

    def test_delete_offer_using_delete(self):
        """Test case for delete_offer_using_delete

        deleteOffer  # noqa: E501
        """
        pass

    def test_get_all_offers_using_get(self):
        """Test case for get_all_offers_using_get

        getAllOffers  # noqa: E501
        """
        pass

    def test_get_offer_using_get(self):
        """Test case for get_offer_using_get

        getOffer  # noqa: E501
        """
        pass

    def test_update_offer_using_put(self):
        """Test case for update_offer_using_put

        updateOffer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
