# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.service_offering_resource_api import ServiceOfferingResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceOfferingResourceApi(unittest.TestCase):
    """ServiceOfferingResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.service_offering_resource_api.ServiceOfferingResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_offering_using_post(self):
        """Test case for create_service_offering_using_post

        createServiceOffering  # noqa: E501
        """
        pass

    def test_delete_service_offering_using_delete(self):
        """Test case for delete_service_offering_using_delete

        deleteServiceOffering  # noqa: E501
        """
        pass

    def test_get_all_service_offerings_using_get(self):
        """Test case for get_all_service_offerings_using_get

        getAllServiceOfferings  # noqa: E501
        """
        pass

    def test_get_service_offering_using_get(self):
        """Test case for get_service_offering_using_get

        getServiceOffering  # noqa: E501
        """
        pass

    def test_update_service_offering_using_put(self):
        """Test case for update_service_offering_using_put

        updateServiceOffering  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
