# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.card_resource_api import CardResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCardResourceApi(unittest.TestCase):
    """CardResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.card_resource_api.CardResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_card_using_post(self):
        """Test case for create_card_using_post

        createCard  # noqa: E501
        """
        pass

    def test_delete_card_using_delete(self):
        """Test case for delete_card_using_delete

        deleteCard  # noqa: E501
        """
        pass

    def test_get_all_cards_using_get(self):
        """Test case for get_all_cards_using_get

        getAllCards  # noqa: E501
        """
        pass

    def test_get_card_using_get(self):
        """Test case for get_card_using_get

        getCard  # noqa: E501
        """
        pass

    def test_update_card_using_put(self):
        """Test case for update_card_using_put

        updateCard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
