# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.com.kodfarki.subscreasy.client.model.saved_card import SavedCard  # noqa: E501
from swagger_client.rest import ApiException


class TestSavedCard(unittest.TestCase):
    """SavedCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSavedCard(self):
        """Test SavedCard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.saved_card.SavedCard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
