# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.subsription_resource_api import SubsriptionResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubsriptionResourceApi(unittest.TestCase):
    """SubsriptionResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.subsription_resource_api.SubsriptionResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_subscription_using_put(self):
        """Test case for cancel_subscription_using_put

        cancelSubscription  # noqa: E501
        """
        pass

    def test_get_active_subscriptions_using_get(self):
        """Test case for get_active_subscriptions_using_get

        getActiveSubscriptions  # noqa: E501
        """
        pass

    def test_get_all_company_subscriptions_using_get(self):
        """Test case for get_all_company_subscriptions_using_get

        getAllCompanySubscriptions  # noqa: E501
        """
        pass

    def test_get_subsription_using_get(self):
        """Test case for get_subsription_using_get

        getSubsription  # noqa: E501
        """
        pass

    def test_start_subscription_using_post(self):
        """Test case for start_subscription_using_post

        startSubscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
