# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.usage_notification_resource_api import UsageNotificationResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsageNotificationResourceApi(unittest.TestCase):
    """UsageNotificationResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.usage_notification_resource_api.UsageNotificationResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_usage_notification_using_post(self):
        """Test case for create_usage_notification_using_post

        createUsageNotification  # noqa: E501
        """
        pass

    def test_delete_usage_notification_using_delete(self):
        """Test case for delete_usage_notification_using_delete

        deleteUsageNotification  # noqa: E501
        """
        pass

    def test_get_all_usage_notifications_using_get(self):
        """Test case for get_all_usage_notifications_using_get

        getAllUsageNotifications  # noqa: E501
        """
        pass

    def test_get_usage_notification_using_get(self):
        """Test case for get_usage_notification_using_get

        getUsageNotification  # noqa: E501
        """
        pass

    def test_update_usage_notification_using_put(self):
        """Test case for update_usage_notification_using_put

        updateUsageNotification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
