# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.history_resource_api import HistoryResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHistoryResourceApi(unittest.TestCase):
    """HistoryResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.history_resource_api.HistoryResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_history_using_post(self):
        """Test case for create_history_using_post

        createHistory  # noqa: E501
        """
        pass

    def test_delete_history_using_delete(self):
        """Test case for delete_history_using_delete

        deleteHistory  # noqa: E501
        """
        pass

    def test_get_all_histories_using_get(self):
        """Test case for get_all_histories_using_get

        getAllHistories  # noqa: E501
        """
        pass

    def test_get_history_using_get(self):
        """Test case for get_history_using_get

        getHistory  # noqa: E501
        """
        pass

    def test_update_history_using_put(self):
        """Test case for update_history_using_put

        updateHistory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
