# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.charging_log_resource_api import ChargingLogResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChargingLogResourceApi(unittest.TestCase):
    """ChargingLogResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.charging_log_resource_api.ChargingLogResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_charging_log_using_post(self):
        """Test case for create_charging_log_using_post

        createChargingLog  # noqa: E501
        """
        pass

    def test_delete_charging_log_using_delete(self):
        """Test case for delete_charging_log_using_delete

        deleteChargingLog  # noqa: E501
        """
        pass

    def test_get_all_charging_logs_using_get(self):
        """Test case for get_all_charging_logs_using_get

        getAllChargingLogs  # noqa: E501
        """
        pass

    def test_get_charging_log_using_get(self):
        """Test case for get_charging_log_using_get

        getChargingLog  # noqa: E501
        """
        pass

    def test_refund_using_post(self):
        """Test case for refund_using_post

        refund  # noqa: E501
        """
        pass

    def test_update_charging_log_using_put(self):
        """Test case for update_charging_log_using_put

        updateChargingLog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
