# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.coupon_resource_api import CouponResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCouponResourceApi(unittest.TestCase):
    """CouponResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.coupon_resource_api.CouponResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_coupon_using_post(self):
        """Test case for create_coupon_using_post

        createCoupon  # noqa: E501
        """
        pass

    def test_delete_coupon_using_delete(self):
        """Test case for delete_coupon_using_delete

        deleteCoupon  # noqa: E501
        """
        pass

    def test_get_all_coupons_using_get(self):
        """Test case for get_all_coupons_using_get

        getAllCoupons  # noqa: E501
        """
        pass

    def test_get_coupon_using_get(self):
        """Test case for get_coupon_using_get

        getCoupon  # noqa: E501
        """
        pass

    def test_update_coupon_using_put(self):
        """Test case for update_coupon_using_put

        updateCoupon  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
