# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.endpoints_api import EndpointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.endpoints_api.EndpointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize_using_put(self):
        """Test case for authorize_using_put

        authorize  # noqa: E501
        """
        pass

    def test_deduct_using_put(self):
        """Test case for deduct_using_put

        deduct  # noqa: E501
        """
        pass

    def test_get_authorized_services_using_get(self):
        """Test case for get_authorized_services_using_get

        getAuthorizedServices  # noqa: E501
        """
        pass

    def test_get_charging_log_by_subscription_using_get(self):
        """Test case for get_charging_log_by_subscription_using_get

        getChargingLogBySubscription  # noqa: E501
        """
        pass

    def test_get_customer_total_amount_using_get(self):
        """Test case for get_customer_total_amount_using_get

        getCustomerTotalAmount  # noqa: E501
        """
        pass

    def test_get_invoice_details_using_get(self):
        """Test case for get_invoice_details_using_get

        getInvoiceDetails  # noqa: E501
        """
        pass

    def test_get_message_template_using_get(self):
        """Test case for get_message_template_using_get

        getMessageTemplate  # noqa: E501
        """
        pass

    def test_get_service_instances_by_subscription_using_get(self):
        """Test case for get_service_instances_by_subscription_using_get

        getServiceInstancesBySubscription  # noqa: E501
        """
        pass

    def test_get_service_offerings_by_subscription_plan_using_get(self):
        """Test case for get_service_offerings_by_subscription_plan_using_get

        getServiceOfferingsBySubscriptionPlan  # noqa: E501
        """
        pass

    def test_get_total_revenue_per_month_using_get(self):
        """Test case for get_total_revenue_per_month_using_get

        getTotalRevenuePerMonth  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
