# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.service_instance_resource_api import ServiceInstanceResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceInstanceResourceApi(unittest.TestCase):
    """ServiceInstanceResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.service_instance_resource_api.ServiceInstanceResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_instance_using_post(self):
        """Test case for create_service_instance_using_post

        createServiceInstance  # noqa: E501
        """
        pass

    def test_delete_service_instance_using_delete(self):
        """Test case for delete_service_instance_using_delete

        deleteServiceInstance  # noqa: E501
        """
        pass

    def test_get_all_service_instances_using_get(self):
        """Test case for get_all_service_instances_using_get

        getAllServiceInstances  # noqa: E501
        """
        pass

    def test_get_service_instance_using_get(self):
        """Test case for get_service_instance_using_get

        getServiceInstance  # noqa: E501
        """
        pass

    def test_update_service_instance_using_put(self):
        """Test case for update_service_instance_using_put

        updateServiceInstance  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
