# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.user_resource_api import UserResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserResourceApi(unittest.TestCase):
    """UserResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.user_resource_api.UserResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_using_post(self):
        """Test case for create_user_using_post

        createUser  # noqa: E501
        """
        pass

    def test_delete_user_using_delete(self):
        """Test case for delete_user_using_delete

        deleteUser  # noqa: E501
        """
        pass

    def test_get_all_users_using_get(self):
        """Test case for get_all_users_using_get

        getAllUsers  # noqa: E501
        """
        pass

    def test_get_authorities_using_get(self):
        """Test case for get_authorities_using_get

        getAuthorities  # noqa: E501
        """
        pass

    def test_get_user_using_get(self):
        """Test case for get_user_using_get

        getUser  # noqa: E501
        """
        pass

    def test_update_user_using_put(self):
        """Test case for update_user_using_put

        updateUser  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
