# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.analytics_resource_api import AnalyticsResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalyticsResourceApi(unittest.TestCase):
    """AnalyticsResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.analytics_resource_api.AnalyticsResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_dashboard_analytics_using_get(self):
        """Test case for get_dashboard_analytics_using_get

        getDashboardAnalytics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
