# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.com.kodfarki.subscreasy.client.model.managed_user_vm import ManagedUserVM  # noqa: E501
from swagger_client.rest import ApiException


class TestManagedUserVM(unittest.TestCase):
    """ManagedUserVM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testManagedUserVM(self):
        """Test ManagedUserVM"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.managed_user_vm.ManagedUserVM()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
