# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.service_resource_api import ServiceResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServiceResourceApi(unittest.TestCase):
    """ServiceResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.service_resource_api.ServiceResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_using_post(self):
        """Test case for create_service_using_post

        createService  # noqa: E501
        """
        pass

    def test_delete_service_using_delete(self):
        """Test case for delete_service_using_delete

        deleteService  # noqa: E501
        """
        pass

    def test_get_all_services_using_get(self):
        """Test case for get_all_services_using_get

        getAllServices  # noqa: E501
        """
        pass

    def test_get_service_using_get(self):
        """Test case for get_service_using_get

        getService  # noqa: E501
        """
        pass

    def test_update_service_using_put(self):
        """Test case for update_service_using_put

        updateService  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
