# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.company_props_resource_api import CompanyPropsResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyPropsResourceApi(unittest.TestCase):
    """CompanyPropsResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.company_props_resource_api.CompanyPropsResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_company_props_using_post(self):
        """Test case for create_company_props_using_post

        createCompanyProps  # noqa: E501
        """
        pass

    def test_delete_company_props_using_delete(self):
        """Test case for delete_company_props_using_delete

        deleteCompanyProps  # noqa: E501
        """
        pass

    def test_get_all_company_props_using_get(self):
        """Test case for get_all_company_props_using_get

        getAllCompanyProps  # noqa: E501
        """
        pass

    def test_get_company_props_by_company_id_using_get(self):
        """Test case for get_company_props_by_company_id_using_get

        getCompanyPropsByCompanyId  # noqa: E501
        """
        pass

    def test_update_company_props_using_put(self):
        """Test case for update_company_props_using_put

        updateCompanyProps  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
