# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from com.kodfarki.subscreasy.client.message_template_resource_api import MessageTemplateResourceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessageTemplateResourceApi(unittest.TestCase):
    """MessageTemplateResourceApi unit test stubs"""

    def setUp(self):
        self.api = com.kodfarki.subscreasy.client.message_template_resource_api.MessageTemplateResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_message_template_using_post(self):
        """Test case for create_message_template_using_post

        createMessageTemplate  # noqa: E501
        """
        pass

    def test_delete_message_template_using_delete(self):
        """Test case for delete_message_template_using_delete

        deleteMessageTemplate  # noqa: E501
        """
        pass

    def test_get_all_message_templates_using_get(self):
        """Test case for get_all_message_templates_using_get

        getAllMessageTemplates  # noqa: E501
        """
        pass

    def test_get_message_template_using_get1(self):
        """Test case for get_message_template_using_get1

        getMessageTemplate  # noqa: E501
        """
        pass

    def test_update_message_template_using_put(self):
        """Test case for update_message_template_using_put

        updateMessageTemplate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
