# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.com.kodfarki.subscreasy.client.model.deduction import Deduction  # noqa: E501
from swagger_client.rest import ApiException


class TestDeduction(unittest.TestCase):
    """Deduction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeduction(self):
        """Test Deduction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.deduction.Deduction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
