# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.com.kodfarki.subscreasy.client.model.charging_log import ChargingLog  # noqa: E501
from swagger_client.rest import ApiException


class TestChargingLog(unittest.TestCase):
    """ChargingLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChargingLog(self):
        """Test ChargingLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.charging_log.ChargingLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
