# coding: utf-8

# flake8: noqa
"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.com.kodfarki.subscreasy.client.model.address import Address
from swagger_client.com.kodfarki.subscreasy.client.model.authority import Authority
from swagger_client.com.kodfarki.subscreasy.client.model.authorization import Authorization
from swagger_client.com.kodfarki.subscreasy.client.model.authorized_services_response import AuthorizedServicesResponse
from swagger_client.com.kodfarki.subscreasy.client.model.cancellation import Cancellation
from swagger_client.com.kodfarki.subscreasy.client.model.charging_log import ChargingLog
from swagger_client.com.kodfarki.subscreasy.client.model.company import Company
from swagger_client.com.kodfarki.subscreasy.client.model.company_props import CompanyProps
from swagger_client.com.kodfarki.subscreasy.client.model.coupon import Coupon
from swagger_client.com.kodfarki.subscreasy.client.model.deduction import Deduction
from swagger_client.com.kodfarki.subscreasy.client.model.deduction_result import DeductionResult
from swagger_client.com.kodfarki.subscreasy.client.model.history import History
from swagger_client.com.kodfarki.subscreasy.client.model.invoice import Invoice
from swagger_client.com.kodfarki.subscreasy.client.model.invoice_request import InvoiceRequest
from swagger_client.com.kodfarki.subscreasy.client.model.managed_user_vm import ManagedUserVM
from swagger_client.com.kodfarki.subscreasy.client.model.message_template import MessageTemplate
from swagger_client.com.kodfarki.subscreasy.client.model.offer import Offer
from swagger_client.com.kodfarki.subscreasy.client.model.payment_card import PaymentCard
from swagger_client.com.kodfarki.subscreasy.client.model.profile_info_vm import ProfileInfoVM
from swagger_client.com.kodfarki.subscreasy.client.model.recurrence_period import RecurrencePeriod
from swagger_client.com.kodfarki.subscreasy.client.model.response_entity import ResponseEntity
from swagger_client.com.kodfarki.subscreasy.client.model.saved_card import SavedCard
from swagger_client.com.kodfarki.subscreasy.client.model.service import Service
from swagger_client.com.kodfarki.subscreasy.client.model.service_instance import ServiceInstance
from swagger_client.com.kodfarki.subscreasy.client.model.service_instance_result import ServiceInstanceResult
from swagger_client.com.kodfarki.subscreasy.client.model.service_offering import ServiceOffering
from swagger_client.com.kodfarki.subscreasy.client.model.service_offering_result import ServiceOfferingResult
from swagger_client.com.kodfarki.subscreasy.client.model.start_subscription_request import StartSubscriptionRequest
from swagger_client.com.kodfarki.subscreasy.client.model.subscriber import Subscriber
from swagger_client.com.kodfarki.subscreasy.client.model.subscription_create_result import SubscriptionCreateResult
from swagger_client.com.kodfarki.subscreasy.client.model.subscription_plan import SubscriptionPlan
from swagger_client.com.kodfarki.subscreasy.client.model.subsription import Subsription
from swagger_client.com.kodfarki.subscreasy.client.model.usage_notification import UsageNotification
from swagger_client.com.kodfarki.subscreasy.client.model.user import User
