# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.com.kodfarki.subscreasy.client.model.company import Company  # noqa: F401,E501


class ManagedUserVM(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'activated': 'bool',
        'authorities': 'list[str]',
        'company': 'Company',
        'created_by': 'str',
        'created_date': 'datetime',
        'email': 'str',
        'first_name': 'str',
        'id': 'int',
        'image_url': 'str',
        'lang_key': 'str',
        'last_modified_by': 'str',
        'last_modified_date': 'datetime',
        'last_name': 'str',
        'login': 'str',
        'password': 'str',
        'reset_date': 'str'
    }

    attribute_map = {
        'activated': 'activated',
        'authorities': 'authorities',
        'company': 'company',
        'created_by': 'createdBy',
        'created_date': 'createdDate',
        'email': 'email',
        'first_name': 'firstName',
        'id': 'id',
        'image_url': 'imageUrl',
        'lang_key': 'langKey',
        'last_modified_by': 'lastModifiedBy',
        'last_modified_date': 'lastModifiedDate',
        'last_name': 'lastName',
        'login': 'login',
        'password': 'password',
        'reset_date': 'resetDate'
    }

    def __init__(self, activated=None, authorities=None, company=None, created_by=None, created_date=None, email=None, first_name=None, id=None, image_url=None, lang_key=None, last_modified_by=None, last_modified_date=None, last_name=None, login=None, password=None, reset_date=None):  # noqa: E501
        """ManagedUserVM - a model defined in Swagger"""  # noqa: E501

        self._activated = None
        self._authorities = None
        self._company = None
        self._created_by = None
        self._created_date = None
        self._email = None
        self._first_name = None
        self._id = None
        self._image_url = None
        self._lang_key = None
        self._last_modified_by = None
        self._last_modified_date = None
        self._last_name = None
        self._login = None
        self._password = None
        self._reset_date = None
        self.discriminator = None

        if activated is not None:
            self.activated = activated
        if authorities is not None:
            self.authorities = authorities
        if company is not None:
            self.company = company
        if created_by is not None:
            self.created_by = created_by
        if created_date is not None:
            self.created_date = created_date
        if email is not None:
            self.email = email
        if first_name is not None:
            self.first_name = first_name
        if id is not None:
            self.id = id
        if image_url is not None:
            self.image_url = image_url
        if lang_key is not None:
            self.lang_key = lang_key
        if last_modified_by is not None:
            self.last_modified_by = last_modified_by
        if last_modified_date is not None:
            self.last_modified_date = last_modified_date
        if last_name is not None:
            self.last_name = last_name
        self.login = login
        if password is not None:
            self.password = password
        if reset_date is not None:
            self.reset_date = reset_date

    @property
    def activated(self):
        """Gets the activated of this ManagedUserVM.  # noqa: E501


        :return: The activated of this ManagedUserVM.  # noqa: E501
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """Sets the activated of this ManagedUserVM.


        :param activated: The activated of this ManagedUserVM.  # noqa: E501
        :type: bool
        """

        self._activated = activated

    @property
    def authorities(self):
        """Gets the authorities of this ManagedUserVM.  # noqa: E501


        :return: The authorities of this ManagedUserVM.  # noqa: E501
        :rtype: list[str]
        """
        return self._authorities

    @authorities.setter
    def authorities(self, authorities):
        """Sets the authorities of this ManagedUserVM.


        :param authorities: The authorities of this ManagedUserVM.  # noqa: E501
        :type: list[str]
        """

        self._authorities = authorities

    @property
    def company(self):
        """Gets the company of this ManagedUserVM.  # noqa: E501


        :return: The company of this ManagedUserVM.  # noqa: E501
        :rtype: Company
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this ManagedUserVM.


        :param company: The company of this ManagedUserVM.  # noqa: E501
        :type: Company
        """

        self._company = company

    @property
    def created_by(self):
        """Gets the created_by of this ManagedUserVM.  # noqa: E501


        :return: The created_by of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this ManagedUserVM.


        :param created_by: The created_by of this ManagedUserVM.  # noqa: E501
        :type: str
        """

        self._created_by = created_by

    @property
    def created_date(self):
        """Gets the created_date of this ManagedUserVM.  # noqa: E501


        :return: The created_date of this ManagedUserVM.  # noqa: E501
        :rtype: datetime
        """
        return self._created_date

    @created_date.setter
    def created_date(self, created_date):
        """Sets the created_date of this ManagedUserVM.


        :param created_date: The created_date of this ManagedUserVM.  # noqa: E501
        :type: datetime
        """

        self._created_date = created_date

    @property
    def email(self):
        """Gets the email of this ManagedUserVM.  # noqa: E501


        :return: The email of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ManagedUserVM.


        :param email: The email of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if email is not None and len(email) > 100:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `100`")  # noqa: E501
        if email is not None and len(email) < 5:
            raise ValueError("Invalid value for `email`, length must be greater than or equal to `5`")  # noqa: E501

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this ManagedUserVM.  # noqa: E501


        :return: The first_name of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this ManagedUserVM.


        :param first_name: The first_name of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if first_name is not None and len(first_name) > 50:
            raise ValueError("Invalid value for `first_name`, length must be less than or equal to `50`")  # noqa: E501
        if first_name is not None and len(first_name) < 0:
            raise ValueError("Invalid value for `first_name`, length must be greater than or equal to `0`")  # noqa: E501

        self._first_name = first_name

    @property
    def id(self):
        """Gets the id of this ManagedUserVM.  # noqa: E501


        :return: The id of this ManagedUserVM.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ManagedUserVM.


        :param id: The id of this ManagedUserVM.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def image_url(self):
        """Gets the image_url of this ManagedUserVM.  # noqa: E501


        :return: The image_url of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this ManagedUserVM.


        :param image_url: The image_url of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if image_url is not None and len(image_url) > 256:
            raise ValueError("Invalid value for `image_url`, length must be less than or equal to `256`")  # noqa: E501
        if image_url is not None and len(image_url) < 0:
            raise ValueError("Invalid value for `image_url`, length must be greater than or equal to `0`")  # noqa: E501

        self._image_url = image_url

    @property
    def lang_key(self):
        """Gets the lang_key of this ManagedUserVM.  # noqa: E501


        :return: The lang_key of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._lang_key

    @lang_key.setter
    def lang_key(self, lang_key):
        """Sets the lang_key of this ManagedUserVM.


        :param lang_key: The lang_key of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if lang_key is not None and len(lang_key) > 5:
            raise ValueError("Invalid value for `lang_key`, length must be less than or equal to `5`")  # noqa: E501
        if lang_key is not None and len(lang_key) < 2:
            raise ValueError("Invalid value for `lang_key`, length must be greater than or equal to `2`")  # noqa: E501

        self._lang_key = lang_key

    @property
    def last_modified_by(self):
        """Gets the last_modified_by of this ManagedUserVM.  # noqa: E501


        :return: The last_modified_by of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._last_modified_by

    @last_modified_by.setter
    def last_modified_by(self, last_modified_by):
        """Sets the last_modified_by of this ManagedUserVM.


        :param last_modified_by: The last_modified_by of this ManagedUserVM.  # noqa: E501
        :type: str
        """

        self._last_modified_by = last_modified_by

    @property
    def last_modified_date(self):
        """Gets the last_modified_date of this ManagedUserVM.  # noqa: E501


        :return: The last_modified_date of this ManagedUserVM.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modified_date

    @last_modified_date.setter
    def last_modified_date(self, last_modified_date):
        """Sets the last_modified_date of this ManagedUserVM.


        :param last_modified_date: The last_modified_date of this ManagedUserVM.  # noqa: E501
        :type: datetime
        """

        self._last_modified_date = last_modified_date

    @property
    def last_name(self):
        """Gets the last_name of this ManagedUserVM.  # noqa: E501


        :return: The last_name of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this ManagedUserVM.


        :param last_name: The last_name of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if last_name is not None and len(last_name) > 50:
            raise ValueError("Invalid value for `last_name`, length must be less than or equal to `50`")  # noqa: E501
        if last_name is not None and len(last_name) < 0:
            raise ValueError("Invalid value for `last_name`, length must be greater than or equal to `0`")  # noqa: E501

        self._last_name = last_name

    @property
    def login(self):
        """Gets the login of this ManagedUserVM.  # noqa: E501


        :return: The login of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this ManagedUserVM.


        :param login: The login of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if login is None:
            raise ValueError("Invalid value for `login`, must not be `None`")  # noqa: E501
        if login is not None and len(login) > 50:
            raise ValueError("Invalid value for `login`, length must be less than or equal to `50`")  # noqa: E501
        if login is not None and len(login) < 1:
            raise ValueError("Invalid value for `login`, length must be greater than or equal to `1`")  # noqa: E501
        if login is not None and not re.search('^[_\'.@A-Za-z0-9-]*$', login):  # noqa: E501
            raise ValueError("Invalid value for `login`, must be a follow pattern or equal to `/^[_'.@A-Za-z0-9-]*$/`")  # noqa: E501

        self._login = login

    @property
    def password(self):
        """Gets the password of this ManagedUserVM.  # noqa: E501


        :return: The password of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ManagedUserVM.


        :param password: The password of this ManagedUserVM.  # noqa: E501
        :type: str
        """
        if password is not None and len(password) > 100:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `100`")  # noqa: E501
        if password is not None and len(password) < 4:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `4`")  # noqa: E501

        self._password = password

    @property
    def reset_date(self):
        """Gets the reset_date of this ManagedUserVM.  # noqa: E501


        :return: The reset_date of this ManagedUserVM.  # noqa: E501
        :rtype: str
        """
        return self._reset_date

    @reset_date.setter
    def reset_date(self, reset_date):
        """Sets the reset_date of this ManagedUserVM.


        :param reset_date: The reset_date of this ManagedUserVM.  # noqa: E501
        :type: str
        """

        self._reset_date = reset_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ManagedUserVM):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
